
export const localimag = {

   // splash: require('../../icons/512x512_without_bg.png'),
    splash: require('../../icons/new_applogo.png'),
    splashback: require('../../icons/Group691.png'),
    splashnew: require('../../icons/new_splash.gif'),
    forgotop: require('../../icons/profile_bg.png'),
    forgobottom: require('../../icons/login_design.png'),
    login: require('../../icons/loginpage.png'),
    language: require('../../icons/language.png'),
    // logcook: require('../../icons/cook2.png'),
    // backimg: require('../../icons/2022-02-27.png'),
    email: require('../../icons/email.png'),
    password: require('../../icons/login_password.png'),
    password1: require('../../icons/padlock.png'),
    // bell: require('../../icons/bell2.png'),
    google: require('../../icons/google.png'),
    facebook: require('../../icons/facebook.png'),
    checkbox1: require('../../icons/box_login.png'),
    checked: require('../../icons/checked.png'),
     checkbox: require('../../icons/checkbox.png'),
    goback: require('../../icons/goback.png'),
    setting_bg: require('../../icons/setting_bg.png'),
    // goback1: require('../../icons/back-button1.png'),
    men: require('../../icons/person.png'),
    email12: require('../../icons/email1.png'),
    bullet_icon: require('../../icons/threedot.png'),
    //pro1: require('../../icons/22.jpg'),
    // pro1: require('../../icons/26-min.jpg'),
    // pro2: require('../../icons/28-min.jpg'),
    // pro3: require('../../icons/24-min.jpg'),
    pro4: require('../../icons/3.jpg'),
    pro5: require('../../icons/5.jpg'),
    Icard: require('../../icons/Icard.jpg'),
   
    arrowlup: require('../../icons/arrow-up.png'),
    arrowldown: require('../../icons/arrow_down.png'),
 
    call: require('../../icons/phone.png'),
    call1: require('../../icons/phone1.png'),
    //logo: require('../../icons/logo.png'),
    logo: require('../../icons/new_applogo.png'),
    active_plus: require('../../icons/active_plus.png'),
    
 

     // ---------------Atul image--------------
  //===========14-03-2022------------
  message1: require('../../icons/Group443.png'),
  delete1:require('../../icons/Group589.png'),
  car1:require('../../icons/car_model_3.png'),
  carm8:require('../../icons/CAR_MAKE8.png'),
  reddo1:require('../../icons/Ellipse50.png'),
  car2:require('../../icons/car_model_1.png'),
  logo1:require('../../icons/CAR_MAKE7.png'),
  blackdo2:require('../../icons/Ellipse54.png'),
  sucess1:require('../../icons/success_bg.png'),
  goback1:require('../../icons/goback.png'),
  right_arrow:require('../../icons/down18-1.png'),
  profile1:require('../../icons/profile_bg.png'),
  man2:require('../../icons/man2.jpg'),
  edit1:require('../../icons/edit2.png'),
  location1:require('../../icons/location2.png'),
  wallet1:require('../../icons/wallet3.png'),
  lang1:require('../../icons/language_profile.png'),
  sett1:require('../../icons/gear4.png'),
  bacKground1:require('../../icons/background.png'),
  addphoto:require('../../icons/add-photo.png'),
  
  camera1:require('../../icons/Group690.png'),
  person1:require('../../icons/person.png'),
  favou1:require('../../icons/favourite.png'),
  right1:require('../../icons/rightarrow8.png'),
  language_selctor:require('../../icons/Group549.png'),
  bell:require('../../icons/bell.png'),
  padlock1:require('../../icons/padlock.png'),
  faq1:require('../../icons/faq.png'),
  term1:require('../../icons/term.png'),
  about1:require('../../icons/aboutus.png'),
  logout1:require('../../icons/logout2.png'),
  rate2:require('../../icons/rateApp.png'),
  share1:require('../../icons/sharing1.png'),
  delete2:require('../../icons/delete1.png'),
  logred2:require('../../icons/logout2.png'),
  user1:require('../../icons/user2.png'),
  email1:require('../../icons/email.png'),
  pen1:require('../../icons/pen2.png'),
  plus1:require('../../icons/plus3.png'),
  privacy1:require('../../icons/privacypolicy.png'),
  homeinactive1:require('../../icons/homeinactive.png'),
  homeactive2:require('../../icons/homeactive.png'),
  myvehicle1:require('../../icons/myvehicles.png'),
 myvehicle2:require('../../icons/myvehicleactive.png'),
 mybookingactive1:require('../../icons/mybookingsActive.png'),
 mybookinfinactive1:require('../../icons/my bookingsuserinactive.png'),
 userinactive1:require('../../icons/userinactive.png'),
  //===========22-03-2022------------
telephone1:require('../../icons/telephone2.png'),
man4:require('../../icons/man3.jpg'),
man5:require('../../icons/3.jpg'),
man6:require('../../icons/4.jpg'),
man7:require('../../icons/5.jpg'),
man8:require('../../icons/6.jpg'),
man9:require('../../icons/8.jpg'),
hyundai1:require('../../icons/hyundai.png'),
 //===========28-03-2022------------
  star1:require('../../icons/star13.png'),
  roundtele:require('../../icons/Group593.png'),
  //===========29-03-2022------------
  map1:require('../../icons/map.png'),
  scooter1:require('../../icons/Group465.png'),
  carwash:require('../../icons/carwash(3)1.png'),
   //===========30-03-2022------------
   celender1:require('../../icons/calendar(7)2.png'),
   arrowfr:require('../../icons/down18-1.png'),
   sucess2:require('../../icons/success_bg.png'),
   washing1:require('../../icons/57556631.png'),
   time1:require('../../icons/clock(3)2.png'),
   //===========31-03-2022------------
   car_img1:require('../../icons/car10.jpg'),
   car_img2:require('../../icons/car13.jpg'),
   car_img3:require('../../icons/car14.jpg'),
   car_img4:require('../../icons/car15.jpg'),
   car_img5:require('../../icons/car16.jpg'),
   car_img6:require('../../icons/car17.jpg'),
   car_img7:require('../../icons/car18.jpg'),
   car_img8:require('../../icons/car20.jpg'),
   carmodel:require('../../icons/carmodel.png'),
   carmodel1:require('../../icons/car_model_4.png'),
   carmodel2:require('../../icons/car_model_5.png'),
   carmodel3:require('../../icons/car_model_6.png'),
//===========31-03-2022------------
united2:require('../../icons/Untitled-1.png'),
padlock4:require('../../icons/password5.png'),
//===========5-03-2022------------

//===========6-03-2022------------
profile3:require('../../icons/userinactive.png'),
service2:require('../../icons/service4.png'),
profile_active:require('../../icons/profile_active.png'),
service5:require('../../icons/service1.png'),
service6:require('../../icons/portfolio2.png'),
person1:require('../../icons/person1.jpg'),
cancel:require('../../icons/cross.png'),
compact4:require('../../icons/car-compact4.png'),
bonus:require('../../icons/bonus.png'),
repair:require('../../icons/car-repair.png'),
offer:require('../../icons/offer.png'),
bottom_right_design:require('../../icons/login_design.png'),
bottom_logo:require('../../icons/background_1.png'),
rating2:require('../../icons/rating2.png'),
activeStar:require('../../icons/activeStar.png'),
unactiveStar:require('../../icons/deactivae_star.png'),
//===========9-03-2022------------
celender2:require('../../icons/clender4.png'),
earning_fill:require('../../icons/earning_fill.png'),

//---------------------Hariom----------------------
new_header: require('../../icons/new_header.png'),
active_notifi_icon:require('../../icons/active_notifi_icon.png'),
deactive_notifi_icon:require('../../icons/deactivate_notification.png'),
forgot_pass_background:require('../../icons/forgot_pass_background.png'),
placeholder_icon : require('../../icons/placeholder_img.png'),
placeholder_camera_icon : require('../../icons/placeholder_camera_icon.png'),
notification_logo : require('../../icons/1024.png'),

}